version: '3.8'

services:
  app:
    image: mydeseret-api:latest
    build: .
    container_name: mydeseret-api
    ports:
      - "8080:8080"
    environment:
      # Now these pull from your .env file too!
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      
      # Secrets
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    restart: always